// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyMoVmAN6ySVcqu17xckf1mIwuRYd6Z0',
    appId: '1:179066162007:web:a187521d90fe1e1c468c12',
    messagingSenderId: '179066162007',
    projectId: 'sugarcheckproject',
    authDomain: 'sugarcheckproject.firebaseapp.com',
    storageBucket: 'sugarcheckproject.firebasestorage.app',
    measurementId: 'G-PSYV81VP8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKTHW3gtUf9xNq3AfE5sI3xWKzDUzkEk',
    appId: '1:179066162007:android:c27da47529cf48f3468c12',
    messagingSenderId: '179066162007',
    projectId: 'sugarcheckproject',
    storageBucket: 'sugarcheckproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUUcfCzM217m9JLiWkKVrjyNxjm4yAUw',
    appId: '1:179066162007:ios:bc28b748f178af0e468c12',
    messagingSenderId: '179066162007',
    projectId: 'sugarcheckproject',
    storageBucket: 'sugarcheckproject.firebasestorage.app',
    iosBundleId: 'com.example.sugarcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUUcfCzM217m9JLiWkKVrjyNxjm4yAUw',
    appId: '1:179066162007:ios:bc28b748f178af0e468c12',
    messagingSenderId: '179066162007',
    projectId: 'sugarcheckproject',
    storageBucket: 'sugarcheckproject.firebasestorage.app',
    iosBundleId: 'com.example.sugarcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPyMoVmAN6ySVcqu17xckf1mIwuRYd6Z0',
    appId: '1:179066162007:web:06e3514b0ef2a795468c12',
    messagingSenderId: '179066162007',
    projectId: 'sugarcheckproject',
    authDomain: 'sugarcheckproject.firebaseapp.com',
    storageBucket: 'sugarcheckproject.firebasestorage.app',
    measurementId: 'G-W5SWD40CQR',
  );
}
